dbus: Fix build/link bug
Fixes problems such as:
undefined reference to `clock_gettime'
undefined reference to `clock_getres'

Signed-off-by: Esben Haabendal <esben.haabendal@prevas.dk>

(cherry picked from commit 241fd2ff5cd24cdb7ed4aee221ae7e0b00720f28)