binutils: Fix build on ARM
cc1: warnings being treated as errors
gas/config/tc-arm.c: In function 'parse_operands':
gas/config/tc-arm.c:1876:27: error: 'firsttype$defined' may be used uninitialized in this function
gas/config/tc-arm.c:1876:27: error: 'firsttype$index' may be used uninitialized in this function

Signed-off-by: Esben Haabendal <esben.haabendal@prevas.dk>

(cherry picked from commit 9e40a1115a5a49ed7bdcc3affd2dd30aa4d83595)