gobject-introspection: Fix build problems with pyexpat module
Fix build problem caused by mismatch between the libexpat version staged
and the host version as needed by the cElementTree Python module:

Traceback (most recent call last):
  File "../tools/g-ir-scanner", line 43, in <module>
    from giscanner.scannermain import scanner_main
  File "/mnt/tmp/oe-lite/core-3.3/work/native/x86_64-build_unknown-linux-gnu/gobject-introspection-0.9.10/src/gobject-introspection-0.9.10/giscanner/scannermain.py", line 34, in <module>
    from giscanner.dumper import compile_introspection_binary
  File "/mnt/tmp/oe-lite/core-3.3/work/native/x86_64-build_unknown-linux-gnu/gobject-introspection-0.9.10/src/gobject-introspection-0.9.10/giscanner/dumper.py", line 26, in <module>
    from .gdumpparser import IntrospectionBinary
  File "/mnt/tmp/oe-lite/core-3.3/work/native/x86_64-build_unknown-linux-gnu/gobject-introspection-0.9.10/src/gobject-introspection-0.9.10/giscanner/gdumpparser.py", line 26, in <module>
    from xml.etree.cElementTree import parse
  File "/usr/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: PyCapsule_Import could not import module "pyexpat"

The libexpat library is not directly needed, so it was not correct to
depend on it here anyway.

Signed-off-by: Esben Haabendal <esben.haabendal@prevas.dk>

(cherry picked from commit bf7b8c9f832b9f42f78b8ff54e614506db57ae6b)